### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by mostafaismail11** [dpeerlab/spectra#19]
week ago, I was running the model perfectly, I am trying to use it today  it returns me super bad error when I try to call the package and modules **"TabError: inconsistent use of tabs and spaces in indentation"**  

from spectra import spectra as spc 
TabError: inconsistent use of tabs and spaces in indentation

from spectra import spectra_util as spc_tl 
TabError: inconsistent use of tabs and spaces in indentation

from spectra import spectra_util as spc_tl
TabError: inconsistent use of tabs and spaces in indentation

I used the original notebook (tutorial notebook) of spectra. 

please I need help, How can I avoid this error.

**Comment by russellkune** [comment]
Let me know if the most recent changes fix the issue.
