### ISSUE TITLE
Example notebook is missing 

### ISSUE THREAD

**Issue by ccruizm** [dpeerlab/spectra#20]
Good day! 

I am eager to test this exciting approach in our dataset. I have seen in several of the previous issues a link to a more detailed and expanded tutorial on how to use the tool (https://github.com/dpeerlab/spectra/blob/main/notebooks/example_notebook.ipynb), but that notebook does not exist. Could you please upload it again?

Thanks in advance, and looking forward to use your tool

**Comment by wallet-maker** [comment]
Dear ccruizm,

thank you for your interest in Spectra. We have replace the old tutorial you are referencing with our new, better and more detailed tutorial you can find here and also use on Google Colab: 

https://github.com/dpeerlab/spectra/blob/main/notebooks/Spectra_Colaboratory_tutorial.ipynb

Let me know if you have any further questions.

Thanks,
Thomas

**Comment by ccruizm** [comment]
Thanks @wallet-maker, for clarifying it! Excited to see how it performs with our dataset.
