### ISSUE TITLE
Error saving / loading when initialize the model with kappa/ rho etc. 

### ISSUE THREAD

**Issue by ruochiz** [dpeerlab/spectra#8]
Hi,

Thank you for creating this amazing tool. I noticed a potential bug when saving/loading models. 

File spectra.py
Line: near 243 & 251.
The dictionary self.rho / self.kappa should be transformed in to nn.ParameterDict after initialization to register the parameters to the state_dict. Otherwise, these parameters won't be saved, and hence raise an error when trying to load trained model from disk. 

The same goes for cases. when use_cell_types = False, kappa and rho should be registered to be saved properly.

**Comment by wallet-maker** [comment]
Hi, 

thank you for your feedback and your suggestions they are much appreciated. Yes, rho and kappa parameters currently have to be initialized identically when you load the model from disk. Do you happen to have the error message when you tried loading the model? 

Thanks,
Thomas

**Comment by ruochiz** [comment]
Error info is like this, 
<img width="1125" alt="CleanShot 2023-01-30 at 10 03 59@2x" src="https://user-images.githubusercontent.com/8788626/215513851-b84b6142-d696-444a-85ad-3e6ea8cab57f.png">
and it can be fixed by
<img width="904" alt="CleanShot 2023-01-30 at 10 05 10@2x" src="https://user-images.githubusercontent.com/8788626/215514065-7e4351da-37ba-422d-87a8-de6f68e68513.png">

The error happens when I run the code following example notebook and later try to reload the trained model. 

Thanks.

**Comment by wallet-maker** [comment]
That's super helpful thank you, we're working to fix that!
